version: '3.8'

services:
  cms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5087:5087"
      - "7096:7096"
    depends_on:
      - db
    extra_hosts:
      - "rabbitmq:127.0.0.1"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SmartCollegeConnection=Server=db;Port=5432;Database=CollegeManagementSystem;User Id=postgres;Password=qwegjghj01;
      - ASPNETCORE_HTTP_PORTS=5087

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=CollegeManagementSystem
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwegjghj01
    volumes:
      - /postgres:/var/lib/postgresql/data