version: '3.8'

services:
  cms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5087:5087"
      - "7096:7096"
    networks:
      - smartcollege_broker-network
      - collegemanagementsystem-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SmartCollegeConnection=Host=db;Port=5432;Database=CollegeManagementSystem;Username=postgres;Password=qwegjghj01;
      - ASPNETCORE_HTTP_PORTS=5087
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5433:5432"
    networks:
      - collegemanagementsystem-network
    environment:
      - POSTGRES_DB=CollegeManagementSystem
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwegjghj01
    volumes:
      - /postgres:/var/lib/postgresql/data

networks:
    smartcollege_broker-network:
        name: smartcollege_broker-network
    collegemanagementsystem-network:
        name: collegemanagementsystem-network
        driver: bridge